experiment:
  directory: tuning
  n_iter: 5
  ablation: 
    dataset.kwargs["dataset"]: [ecoli, glass, letter, optdigits, page-blocks, pendigits, satimage, vehicle, yeast]
    target_policy.kwargs.temperature: [10, -10]
    logging_policy.kwargs.temperature: [3, 1, 0, -1, -3]
dataset:
  module: openml
  kwargs:
    dataset: ecoli
    version: 1
  preprocessing:
    - name: ordinal_label
  eval_model_split: 0.5
logging_policy:
  name: softmax
  kwargs:
    temperature: 1
    model_kwargs:
      max_iter: 1000000
    preprocessing:
      - name: subsample
        kwargs:
          n: 1.0
          replace: True
target_policy:
  name: softmax
  kwargs:
    temperature: 10
    model_kwargs:
      max_iter: 1000000
    preprocessing:
      - name: subsample
        kwargs:
          n: 1.0
          replace: True
estimators:
  - name: TruncatedIPS
    printname: TruncatedIPS Original Tuning/Theory
  - name: TruncatedIPS
    printname: TruncatedIPS \ensuremath{\tt OCV_{IPS}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
      kwargs:
        valid_estimator: IPS
  - name: TruncatedIPS
    printname: TruncatedIPS \ensuremath{\tt OCV_{DR}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
  - name: TruncatedIPS
    printname: TruncatedIPS \textsc{Slope}
    hyperparameters: dynamic
    tuning:
      tuner: SLOPE
  - name: TruncatedIPS
    printname: TruncatedIPS \ensuremath{\tt PAS{\text -}IF}
    hyperparameters: dynamic
    tuning:
      name: PASIF
  - name: SwitchDR
    printname: \textsc{Switch}-DR Original Tuning/Theory
    hyperparameters: dynamic
    tuning:
      tuner: SwitchDR
  - name: SwitchDR
    printname: \textsc{Switch}-DR \ensuremath{\tt OCV_{IPS}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
      kwargs:
        valid_estimator: IPS
  - name: SwitchDR
    printname: \textsc{Switch}-DR \ensuremath{\tt OCV_{DR}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
  - name: SwitchDR
    printname: \textsc{Switch}-DR \textsc{Slope}
    hyperparameters: dynamic
    tuning:
      tuner: SLOPE
  - name: SwitchDR
    printname: \textsc{Switch}-DR \ensuremath{\tt PAS{\text -}IF}
    hyperparameters: dynamic
    tuning:
      tuner: PASIF
  - name: CAB
    printname: CAB \ensuremath{\tt OCV_{IPS}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
      kwargs:
        valid_estimator: IPS
  - name: CAB
    printname: CAB \ensuremath{\tt OCV_{DR}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
  - name: CAB
    printname: CAB \textsc{Slope}
    hyperparameters: dynamic
    tuning:
      tuner: SLOPE
  - name: CAB
    printname: CAB \ensuremath{\tt PAS{\text -}IF}
    hyperparameters: dynamic
    tuning:
      tuner: PASIF
  - name: DRos
    printname: DRos Original Tuning/Theory
    hyperparameters: dynamic
    tuning:
      tuner: DRs
  - name: DRos
    printname: DRos \ensuremath{\tt OCV_{IPS}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
      kwargs:
        valid_estimator: IPS
  - name: DRos
    printname: DRos \ensuremath{\tt OCV_{DR}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
  - name: DRos
    printname: DRos \textsc{Slope}
    hyperparameters: dynamic
    tuning:
      tuner: SLOPE
  - name: DRos
    printname: DRos \ensuremath{\tt PAS{\text -}IF}
    hyperparameters: dynamic
    tuning:
      tuner: PASIF
  - name: DRps
    printname: DRps Original Tuning/Theory
    hyperparameters: dynamic
    tuning:
      tuner: DRs
  - name: DRps
    printname: DRps \ensuremath{\tt OCV_{IPS}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
      kwargs:
        valid_estimator: IPS
  - name: DRps
    printname: DRps \ensuremath{\tt OCV_{DR}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
  - name: DRps
    printname: DRps \textsc{Slope}
    hyperparameters: dynamic
    tuning:
      tuner: SLOPE
  - name: DRps
    printname: DRps \ensuremath{\tt PAS{\text -}IF}
    hyperparameters: dynamic
    tuning:
      tuner: PASIF
  - name: SubGaussianIPS
    printname: IPS-$\lambda$ Original Tuning/Theory
  - name: SubGaussianIPS
    printname: IPS-$\lambda$ \ensuremath{\tt OCV_{IPS}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
      kwargs:
        valid_estimator: IPS
  - name: SubGaussianIPS
    printname: IPS-$\lambda$ \ensuremath{\tt OCV_{DR}}
    hyperparameters: dynamic
    tuning:
      tuner: OCV
  - name: SubGaussianIPS
    printname: IPS-$\lambda$ \textsc{Slope}
    hyperparameters: dynamic
    tuning:
      tuner: SLOPE
  - name: SubGaussianIPS
    printname: IPS-$\lambda$ \ensuremath{\tt PAS{\text -}IF}
    hyperparameters: dynamic
    tuning:
      tuner: PASIF
  - name: GroupIPS
    printname: GroupIPS \ensuremath{\tt OCV_{IPS}}
    hyperparameters:
      K: [2, 4, 8, 16, 32]
    tuning:
      tuner: OCV
      kwargs:
        valid_estimator: IPS
  - name: GroupIPS
    printname: GroupIPS \ensuremath{\tt OCV_{DR}}
    hyperparameters:
      K: [2, 4, 8, 16, 32]
    tuning:
      tuner: OCV
  - name: GroupIPS
    printname: GroupIPS \textsc{Slope}
    hyperparameters:
      K: [32, 16, 8, 4, 2]
    tuning:
      tuner: SLOPE
  - name: GroupIPS
    printname: GroupIPS \ensuremath{\tt PAS{\text -}IF}
    hyperparameters:
      K: [2, 4, 8, 16, 32]
    tuning:
      tuner: PASIF
  - name: EstimatorSelection
    printname: Everything \ensuremath{\tt OCV_{IPS}}
    hyperparameters: dynamic
    kwargs:
      hyperparameters:
        - name: SwitchDR
          hyperparameters: dynamic
        - name: TruncatedIPS
          hyperparameters: dynamic
        - name: DRos
          hyperparameters: dynamic
        - name: DRps
          hyperparameters: dynamic
        - name: CAB
          hyperparameters: dynamic
        - name: SubGaussianIPS
          hyperparameters: dynamic
        - name: GroupIPS
          hyperparameters:
            K: [32, 16, 8, 4, 2]
    tuning:
      tuner: OCV
      kwargs:
        valid_estimator: IPS 
  - name: EstimatorSelection
    printname: Everything \ensuremath{\tt OCV_{DR}}
    hyperparameters: dynamic
    kwargs:
      hyperparameters:
        - name: SwitchDR
          hyperparameters: dynamic
        - name: TruncatedIPS
          hyperparameters: dynamic
        - name: DRos
          hyperparameters: dynamic
        - name: DRps
          hyperparameters: dynamic
        - name: CAB
          hyperparameters: dynamic
        - name: SubGaussianIPS
          hyperparameters: dynamic
        - name: GroupIPS
          hyperparameters:
            K: [32, 16, 8, 4, 2]
    tuning:
      tuner: OCV
  - name: EstimatorSelection
    printname: Everything \ensuremath{\tt PAS{\text -}IF}
    hyperparameters: dynamic
    kwargs:
      hyperparameters:
        - name: SwitchDR
          hyperparameters: dynamic
        - name: TruncatedIPS
          hyperparameters: dynamic
        - name: DRos
          hyperparameters: dynamic
        - name: DRps
          hyperparameters: dynamic
        - name: CAB
          hyperparameters: dynamic
        - name: SubGaussianIPS
          hyperparameters: dynamic
        - name: GroupIPS
          hyperparameters:
            K: [32, 16, 8, 4, 2]
    tuning:
      tuner: PASIF
plot:
  type: tuningplot
  xlabel: Estimator
